version: '3'

services:
  magic-0-php:
    build: .
    security_opt:
      - seccomp:seccomp.json

  magic-0-nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/:/var/www/html
    ports:
      - "25000:80"
    depends_on:
      - magic-0-php
    restart: always